import {
  Zap,
  Scale,
  Crown,
  MessageSquarePlus,
  Clock,
  Shield,
  Sparkles,
  Layout,
  Globe,
  GraduationCap,
  Building2,
  Users,
  FileCheck,
  TrendingUp,
} from "lucide-react";

export const plans = [
  {
    name: "Grátis",
    price: "0",
    period: "para sempre",
    description: "Para conhecer a plataforma",
    icon: Zap,
    color: "gray",
    features: [
      "3 cálculos por dia",
      "6 mensagens",
      "2 petições com marca d'água",
    ],
    notIncluded: ["Gestão de Múltiplos Usuários"],
    cta: "Assinar Agora",
    popular: false,
  },
  {
    name: "Estudante Basic",
    price: "19,90",
    period: "/mês",
    description: "Foco em pesquisa acadêmica",
    icon: GraduationCap,
    color: "gray",
    features: [
      "3 documentos por dia",
      "IA acadêmica avançada",
      "Resumos dinâmicos de matéria",
      "IA ensina como professor",
      "Sem marca d'água",
    ],
    notIncluded: [
      "Simulador OAB / TCC",
      "IA com Visão (Ler Documentos)",
      "Gestão de Clientes",
    ],
    cta: "Assine Agora",
    popular: false,
  },
  {
    name: "Estudante Pro",
    price: "29,90",
    period: "/mês",
    description: "OAB, TCC e Estágio",
    icon: GraduationCap,
    color: "accent",
    features: [
      "Tudo do Estudante Basic",
      "Simuladores de peças OAB (IA)",
      "Assistente completo de TCC",
      "Central Acadêmica exclusiva",
      "IA com Visão (Análise de PDFs)",
      "8 documentos por dia",
      "Deep Research (1/dia)",
    ],
    notIncluded: [
      "Gestão de Clientes e Processos",
      "Gerador Judicial Automatizado",
    ],
    cta: "Assine Agora",
    popular: true,
  },
  {
    name: "Estudante Pesquisador",
    price: "59,90",
    period: "/mês",
    description: "TCCs, Artigos e Doutorado",
    icon: GraduationCap,
    color: "accent",
    features: [
      "Tudo do Estudante Pro",
      "Deep Research (5/dia)",
      "Análises profundas na Web",
      "Resumo Inteligente de Livros",
      "15 documentos por dia",
      "IA com Raciocínio Avançado",
    ],
    notIncluded: [],
    cta: "Assine Agora",
    popular: false,
  },
  {
    name: "Advogado Starter",
    price: "127,00",
    period: "/mês",
    description: "Gestão Profissional Solo",
    icon: Scale,
    color: "accent",
    features: [
      "Plataforma Solo (1 Usuário)",
      "Gestão de Clientes Avançada",
      "Controle de Processos e Fichas",
      "Análise de Processos por IA",
      "Área Acadêmica Liberada",
      "Cálculos Jurídicos Ilimitados",
    ],
    notIncluded: [
      "Gerador de Documentos Jurídicos",
      "Coleta de Assinaturas (PDFs)",
      "Agenda Pessoal / Eventos",
      "Gestão de Equipe",
    ],
    cta: "Assine Agora",
    popular: false,
  },
  {
    name: "Advogado Growth",
    price: "147",
    period: "/mês",
    description: "Produtividade para a Equipe",
    icon: Crown,
    color: "accent",
    features: [
      "Até 2 Usuários inclusos (Equipe)",
      "Gerenciador de Documentos por IA",
      "Assinador Duplo de Contratos (PDF)",
      "Dashboard ERP + BI Jurídico",
      "Agenda Completa de Prazos/Eventos",
      "Todas funções do Advogado Starter",
    ],
    notIncluded: [
      "Controle Financeiro / Honorários",
      "Análise de Acervo e Auditoria de Processos",
    ],
    cta: "Assine Agora",
    popular: true,
  },
  {
    name: "Escritório Master",
    price: "497",
    period: "/mês",
    description: "Controle Total da Banca",
    icon: Building2,
    color: "accent",
    features: [
      "Até 4 Usuários Inclusos",
      "Módulo Financeiro (Honorários/Despesas)",
      "Análise de Acervo e Auditoria de Processos por IA",
      "Gestão Completa de Permissões/Perfis",
      "Todos os recursos do Advogado Growth",
      "Histórico de Uso da IA da Equipe",
    ],
    notIncluded: [],
    cta: "Assine Agora",
    popular: false,
  },
  {
    name: "Enterprise",
    price: "Sob Consulta",
    period: "",
    description: "Grandes departamentos e órgãos",
    icon: Globe,
    color: "accent",
    features: [
      "Usuários ilimitados",
      "Gestor de contas dedicado",
      "Personalização White Label",
      "Treinamento Online",
    ],
    notIncluded: [],
    cta: "Fale Conosco",
    popular: false,
  },
];

export const featureCards = [
  {
    icon: GraduationCap,
    title: "Simulador de Peças OAB",
    desc: "Treine a elaboração de peças completas para a 2ª fase com cronograma, gabaritos oficiais e correção didática automática.",
    color: "amber",
    gradient: "from-amber-500/20 to-amber-600/5",
  },
  {
    icon: Sparkles,
    title: "Professor IA & Didática",
    desc: "Entenda a lógica de cada tese e parágrafo. A IA ensina e explica a fundamentação de forma didática e simplificada.",
    color: "indigo",
    gradient: "from-indigo-500/20 to-indigo-600/5",
  },
  {
    icon: FileCheck,
    title: "Assistente de TCC e Artigos",
    desc: "Estruture capítulos, desenvolva revisões bibliográficas e formate referências conforme as regras da ABNT rapidamente.",
    color: "green",
    gradient: "from-green-500/20 to-green-600/5",
  },
  {
    icon: MessageSquarePlus,
    title: "Petições para Faculdade e Estágio",
    desc: "Gere modelos e peças para as disciplinas práticas da faculdade ou petições reais para turbinar o seu estágio supervisionado.",
    color: "blue",
    gradient: "from-blue-500/20 to-blue-600/5",
  },
  {
    icon: Clock,
    title: "Pesquisa Rápida e Resumos",
    desc: "Acesse decisões de tribunais e doutrinas resumidas pela IA em linguagem simples para agilizar seus estudos e fichamentos.",
    color: "accent",
    gradient: "from-accent/20 to-accent-light/5",
  },
  {
    icon: Shield,
    title: "Leitura de PDFs e Provas",
    desc: "Suba apostilas, provas anteriores da OAB ou códigos de leis e faça perguntas diretas para a IA encontrar o que você precisa.",
    color: "purple",
    gradient: "from-purple-500/20 to-purple-600/5",
  },
];

export const testimonials = [
  {
    name: "Dr. Lucas Mendes",
    role: "Advogado Trabalhista",
    text: "Reduzi o tempo de cálculos de horas para segundos. Ferramenta indispensável.",
  },
  {
    name: "Dra. Beatriz Rocha",
    role: "Civilista",
    text: "A qualidade das petições geradas pela I.A. é surpreendente. Economizo 70% do meu tempo.",
  },
  {
    name: "Dr. Felipe Santos",
    role: "Estudante de Direito",
    text: "Me ajudou muito na faculdade. O plano estudante é muito acessível.",
  },
];

export const colorMap = {
  blue: {
    bg: "bg-blue-100 dark:bg-blue-900/30",
    text: "text-blue-600 dark:text-blue-400",
    border: "border-blue-200 dark:border-blue-800",
  },
  green: {
    bg: "bg-green-100 dark:bg-green-900/30",
    text: "text-green-600 dark:text-green-400",
    border: "border-green-200 dark:border-green-800",
  },
  purple: {
    bg: "bg-purple-100 dark:bg-purple-900/30",
    text: "text-purple-600 dark:text-purple-400",
    border: "border-purple-200 dark:border-purple-800",
  },
  orange: {
    bg: "bg-orange-100 dark:bg-orange-900/30",
    text: "text-orange-600 dark:text-orange-400",
    border: "border-orange-200 dark:border-orange-800",
  },
  indigo: {
    bg: "bg-indigo-100 dark:bg-indigo-900/30",
    text: "text-indigo-600 dark:text-indigo-400",
    border: "border-indigo-200 dark:border-indigo-800",
  },
  gray: {
    bg: "bg-gray-100 dark:bg-gray-800/50",
    text: "text-gray-600 dark:text-gray-400",
    border: "border-gray-200 dark:border-gray-700",
  },
  accent: {
    bg: "bg-accent/10",
    text: "text-accent",
    border: "border-accent/30",
  },
  amber: {
    bg: "bg-amber-100 dark:bg-amber-900/30",
    text: "text-amber-600 dark:text-amber-400",
    border: "border-amber-200 dark:border-amber-800",
  },
};
