import {
  Zap,
  Scale,
  Crown,
  MessageSquarePlus,
  Clock,
  Shield,
  Sparkles,
  Layout,
  Globe,
  GraduationCap,
  Building2,
  Users,
  FileCheck,
  TrendingUp,
} from "lucide-react";

export const plans = [
  {
    name: "Grátis",
    price: "0",
    period: "para sempre",
    description: "Para conhecer a plataforma",
    icon: Zap,
    color: "gray",
    features: [
      "3 cálculos por dia",
      "6 mensagens",
      "2 petições com marca d'água",
    ],
    notIncluded: ["Gestão de Múltiplos Usuários"],
    cta: "Assinar Agora",
    popular: false,
  },
  {
    name: "Estudante Basic",
    price: "17,90",
    period: "/mês",
    description: "Foco em pesquisa acadêmica",
    icon: GraduationCap,
    color: "gray",
    features: [
      "5 documentos por dia",
      "IA acadêmica avançada",
      "Resumos dinâmicos de matéria",
      "IA ensina como professor",
      "Sem marca d'água",
    ],
    notIncluded: [
      "Simulador OAB / TCC",
      "IA com Visão (Ler Documentos)",
      "Gestão de Clientes",
    ],
    cta: "Assine Agora",
    popular: false,
  },
  {
    name: "Estudante Pro",
    price: "34",
    period: "/mês",
    description: "OAB, TCC e Estágio",
    icon: GraduationCap,
    color: "accent",
    features: [
      "Tudo do Estudante Basic",
      "Simuladores de peças OAB (IA)",
      "Assistente completo de TCC",
      "Central Acadêmica exclusiva",
      "IA com Visão (Análise de PDFs)",
      "12 documentos gerados",
    ],
    notIncluded: [
      "Gestão de Clientes e Processos",
      "Gerador Judicial Automatizado",
    ],
    cta: "Assine Agora",
    popular: true,
  },
  {
    name: "Estudante Pesquisador",
    price: "89,90",
    period: "/mês",
    description: "TCCs, Artigos e Doutorado",
    icon: GraduationCap,
    color: "accent",
    features: [
      "Tudo do Estudante Pro",
      "Deep Research (5/dia)",
      "Análises profundas na Web",
      "Resumo Inteligente de Livros",
      "30 documentos gerados",
      "IA com Raciocínio Avançado",
    ],
    notIncluded: [
      "Gestão de Clientes e Processos",
    ],
    cta: "Assine Agora",
    popular: false,
  },
  {
    name: "Advogado Starter",
    price: "127,00",
    period: "/mês",
    description: "Gestão Profissional Solo",
    icon: Scale,
    color: "accent",
    features: [
      "Plataforma Solo (1 Usuário)",
      "Gestão de Clientes Avançada",
      "Controle de Processos e Fichas",
      "Análise de Processos por IA",
      "Área Acadêmica Liberada",
      "Cálculos Jurídicos Ilimitados",
    ],
    notIncluded: [
      "Gerador de Documentos Jurídicos",
      "Coleta de Assinaturas (PDFs)",
      "Agenda Pessoal / Eventos",
      "Gestão de Equipe",
    ],
    cta: "Assine Agora",
    popular: false,
  },
  {
    name: "Advogado Growth",
    price: "147",
    period: "/mês",
    description: "Produtividade para a Equipe",
    icon: Crown,
    color: "accent",
    features: [
      "Até 2 Usuários inclusos (Equipe)",
      "Gerenciador de Documentos por IA",
      "Assinador Duplo de Contratos (PDF)",
      "Dashboard ERP + BI Jurídico",
      "Agenda Completa de Prazos/Eventos",
      "Todas funções do Advogado Starter",
    ],
    notIncluded: [
      "Controle Financeiro / Honorários",
      "Análise de Acervo e Auditoria de Processos",
    ],
    cta: "Assine Agora",
    popular: true,
  },
  {
    name: "Escritório Master",
    price: "497",
    period: "/mês",
    description: "Controle Total da Banca",
    icon: Building2,
    color: "accent",
    features: [
      "Até 4 Usuários Inclusos",
      "Módulo Financeiro (Honorários/Despesas)",
      "Análise de Acervo e Auditoria de Processos por IA",
      "Gestão Completa de Permissões/Perfis",
      "Todos os recursos do Advogado Growth",
      "Histórico de Uso da IA da Equipe",
    ],
    notIncluded: [],
    cta: "Assine Agora",
    popular: false,
  },
  {
    name: "Enterprise",
    price: "Sob Consulta",
    period: "",
    description: "Grandes departamentos e órgãos",
    icon: Globe,
    color: "accent",
    features: [
      "Usuários ilimitados",
      "Gestor de contas dedicado",
      "Personalização White Label",
      "Treinamento Online",
    ],
    notIncluded: [],
    cta: "Fale Conosco",
    popular: false,
  },
];

export const featureCards = [
  {
    icon: MessageSquarePlus,
    title: "Petições e Peças Técnicas",
    desc: "Elabore peças processuais fundamentadas com doutrina consagrada e jurisprudência qualificada de tribunais de forma precisa.",
    color: "blue",
    gradient: "from-blue-500/20 to-blue-600/5",
  },
  {
    icon: Clock,
    title: "Cálculos Judiciais Precisos",
    desc: "Liquidação de sentenças, atualizações monetárias, cálculo de juros complexos e verbas trabalhistas com precisão garantida.",
    color: "accent",
    gradient: "from-accent/20 to-accent-light/5",
  },
  {
    icon: Shield,
    title: "Segurança e Anonimização LGPD",
    desc: "Criptografia de nível bancário e módulo inteligente para anonimização automática de dados sensíveis dos seus clientes.",
    color: "green",
    gradient: "from-green-500/20 to-green-600/5",
  },
  {
    icon: TrendingUp,
    title: "ERP e BI de Alta Performance",
    desc: "Organize prazos processuais automáticos, gerencie a carteira de clientes ativos e monitore os dados de performance da banca.",
    color: "purple",
    gradient: "from-purple-500/20 to-purple-600/5",
  },
  {
    icon: FileCheck,
    title: "Módulo de Assinatura Digital",
    desc: "Envie procurações e contratos de honorários diretamente pela plataforma e acompanhe as assinaturas com total validade jurídica.",
    color: "orange",
    gradient: "from-orange-500/20 to-orange-600/5",
  },
  {
    icon: Sparkles,
    title: "Copiloto Jurídico Sênior",
    desc: "Suporte consultivo inteligente para análise de riscos processuais, revisão e estruturação de teses jurídicas de alto impacto.",
    color: "indigo",
    gradient: "from-indigo-500/20 to-indigo-600/5",
  },
  {
    icon: GraduationCap,
    title: "Central de Estudos e OAB",
    desc: "Simuladores especializados de peças práticas da OAB e apoio metodológico avançado para pesquisas acadêmicas e TCC.",
    color: "amber",
    gradient: "from-amber-500/20 to-amber-600/5",
  },
];

export const testimonials = [
  {
    name: "Dr. Lucas Mendes",
    role: "Advogado Trabalhista",
    text: "Reduzi o tempo de cálculos de horas para segundos. Ferramenta indispensável.",
  },
  {
    name: "Dra. Beatriz Rocha",
    role: "Civilista",
    text: "A qualidade das petições geradas pela I.A. é surpreendente. Economizo 70% do meu tempo.",
  },
  {
    name: "Dr. Felipe Santos",
    role: "Estudante de Direito",
    text: "Me ajudou muito na faculdade. O plano estudante é muito acessível.",
  },
];

export const colorMap = {
  blue: {
    bg: "bg-blue-100 dark:bg-blue-900/30",
    text: "text-blue-600 dark:text-blue-400",
    border: "border-blue-200 dark:border-blue-800",
  },
  green: {
    bg: "bg-green-100 dark:bg-green-900/30",
    text: "text-green-600 dark:text-green-400",
    border: "border-green-200 dark:border-green-800",
  },
  purple: {
    bg: "bg-purple-100 dark:bg-purple-900/30",
    text: "text-purple-600 dark:text-purple-400",
    border: "border-purple-200 dark:border-purple-800",
  },
  orange: {
    bg: "bg-orange-100 dark:bg-orange-900/30",
    text: "text-orange-600 dark:text-orange-400",
    border: "border-orange-200 dark:border-orange-800",
  },
  indigo: {
    bg: "bg-indigo-100 dark:bg-indigo-900/30",
    text: "text-indigo-600 dark:text-indigo-400",
    border: "border-indigo-200 dark:border-indigo-800",
  },
  gray: {
    bg: "bg-gray-100 dark:bg-gray-800/50",
    text: "text-gray-600 dark:text-gray-400",
    border: "border-gray-200 dark:border-gray-700",
  },
  accent: {
    bg: "bg-accent/10",
    text: "text-accent",
    border: "border-accent/30",
  },
  amber: {
    bg: "bg-amber-100 dark:bg-amber-900/30",
    text: "text-amber-600 dark:text-amber-400",
    border: "border-amber-200 dark:border-amber-800",
  },
};
